services:
  - type: web
    name: smart-sampah-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: JWT_SECRET
        value: yourSecretKeyHere
    autoDeploy: true
